# In case you're using more than one container, don't forget to change the host_port of each container. 

version: '3'
services:
  node1:
    build: 
      context: .
      dockerfile: Dockerfile
    image: loureirovini/docker-website:latest
    container_name: node
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    networks:
      - contact-network
    volumes:
      - ./:/app
      - /app/node_modules

networks:
  contact-network:
    driver: bridge